name: Generate Picture of the Day
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install node dependencies
      shell: bash
      run: npm ci
    - name: Get previous picture-of-the-day.json if available
      shell: bash
      run: >
        mkdir -p picture-of-the-day &&
        touch picture-of-the-day/picture-of-the-day.json &&
        git show origin/profile:picture-of-the-day/picture-of-the-day.json > picture-of-the-day/picture-of-the-day.json || true
    - name: Get picture of the Day
      env:
        PICTURE_OF_THE_DAY_GOOGLE_CLIENT_ID: ${{ secrets.PICTURE_OF_THE_DAY_GOOGLE_CLIENT_ID }}
        PICTURE_OF_THE_DAY_GOOGLE_CLIENT_SECRET: ${{ secrets.PICTURE_OF_THE_DAY_GOOGLE_CLIENT_SECRET }}
        PICTURE_OF_THE_DAY_GOOGLE_REFRESH_TOKEN: ${{ secrets.PICTURE_OF_THE_DAY_GOOGLE_REFRESH_TOKEN }}
      shell: bash
      run: >
        bin/picture-of-the-day.js
        --output picture-of-the-day
        --album 'Picture of the Day'
