name: Generate picture of the day reactions

concurrency:
  group: singular

on:
  issues:
    types: [ labeled ]

jobs:
  generate_reactions:
    if: "github.event.label.name == 'reaction:type: picture-of-the-day'"
    name: Generate profile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: profile
      - uses: ./.github/actions/generate-picture-of-the-day-reactions
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/generate-profile
      - uses: EndBug/add-and-commit@v8
        name: Commit files
        with:
          add: '.'
          author_name: 'Botmar 🤖'
          author_email: botmar@dels.ink
          message: 'Publishing generated profile 🎉'
